### PR TITLE
fix(accordion-react): use div to contain title text to avoid inline bug

### PR DESCRIPTION
**Pull request by stianlik**
affects: @fremtind/jkl-accordion-react

ISSUES CLOSED: #397

## 📥 Proposed changes

Use div instead of span to ensure that padding works consistently (i.e. block level element).

## ☑️ Submission checklist

-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [x] `yarn build` works locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

## 💬 Further comments

Another alternative is to use CSS in the accordion package.

### CODE REVIEW

**Comment by stianlik** [comment]
@piofinn PR updated accordingly.

**Comment by piofinn** [comment]
> `Author: Pio Rasch-Halvorsen <pio.rasch-halvorsen@fremtind.no>`

Haha, oops! 😅 Thanks for fixing that as well!

**Comment by piofinn** [comment]
By the way: In the newest version of the AUW front page I see that you have implemented [the new accordion design](https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=169%3A4517) (WIP). You are welcome to create a pull request with these changes as well!

**Comment by stianlik** [comment]
@piofinn See  #404 :)

**Pull request merged**
