### PR TITLE
docs(autosuggest): move experimental icon to end of title

### PR DESCRIPTION
**Pull request by piofinn**
## 📥 Proposed changes

Move the experimental icon to the end of the title for Autosuggest to improve alignment in menus.
Use a soft hyphen at the start to keep sorting order.

**Before**:
Skjermbilde 2020-08-27 kl  14 45 57
**After**:
Skjermbilde 2020-08-27 kl  14 46 04

## ☑️ Submission checklist

-   [x] I have read the [CONTRIBUTING](https://github.com/fremtind/jokul/blob/master/CONTRIBUTING.md) doc
-   [x] `yarn build` works locally with my changes
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] I have added necessary documentation (if appropriate)

## 💬 Further comments

affects: @fremtind/jkl-text-input-react.

### CODE REVIEW

**Comment by Steinop** [comment]
This icon is not compliant to the corporate identity. On the plus side it is extremely visible but wonder if we really need to give that much focus to an experimental component as we already have got a huge messagebox on the component page?

**Review by lfbergee — APPROVED** [review]

**Comment by lfbergee** [comment]
Jeg har ingen sterke feelings her. Generelt er det ikke så fryktelig smart å bruke emojiis, så sånn sett burde vi kanskje hatt et eget ikon. Tror fortsatt er det et poeng å dra ut den infoen i meny/sidemenyen.

**Comment by piofinn** [comment]
Jeg merger denne så lenge, så kan vi finne en bedre løsning til uka 😊 Laget et issue: #1282

**Comment by Steinop** [comment]
Den er god 😁

**Pull request merged**
